/**
 * Job Notification Tracker — Local dataset of 60 realistic Indian tech jobs.
 * Unique IDs, unique content. No backend.
 */

window.JOB_DATA = [
  {
    id: "j1",
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://www.amazon.jobs/en/jobs/IN-SDE-INTERN-001",
    description: "Work on real customer-facing projects alongside experienced engineers. You will design, implement and deploy solutions that impact millions of customers. We look for strong problem-solving skills and passion for building scalable systems."
  },
  {
    id: "j2",
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL", "Communication"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "3–5 LPA",
    applyUrl: "https://careers.tcs.com/GET-2024",
    description: "TCS GET program offers structured training and hands-on project experience. You will be assigned to a project in your first year and mentored by senior engineers. Strong fundamentals in programming and willingness to learn new technologies are essential."
  },
  {
    id: "j3",
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "Redis", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://razorpay.com/jobs/junior-backend-2024",
    description: "Build and maintain payment APIs that power millions of transactions. You will work on scalability, reliability and security of our backend services. Experience with any backend stack and understanding of databases is required."
  },
  {
    id: "j4",
    title: "Frontend Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://www.flipkartcareers.com/frontend-intern",
    description: "Contribute to user-facing web experiences used by millions. You will implement responsive components, integrate with APIs and ensure performance. Knowledge of React or similar framework and modern CSS is expected."
  },
  {
    id: "j5",
    title: "QA Intern",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "SQL", "JIRA", "Test Cases"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹15k–₹30k/month Internship",
    applyUrl: "https://careers.wipro.com/qa-intern",
    description: "Learn software quality assurance in a structured environment. You will write test cases, execute tests and report defects. Basic understanding of software development lifecycle and attention to detail are important."
  },
  {
    id: "j6",
    title: "Data Analyst Intern",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Python", "Data Visualization"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://careers.swiggy.com/data-intern",
    description: "Analyze data to drive decisions for India's largest food delivery platform. You will work with large datasets, build reports and dashboards. Strong analytical thinking and familiarity with SQL or Python is preferred."
  },
  {
    id: "j7",
    title: "Java Developer (0-1)",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "SQL", "REST"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.infosys.com/careers/java-0-1",
    description: "Develop and maintain enterprise Java applications. You will work on backend services, integrate with databases and follow coding standards. Training on our stack will be provided. Strong Java fundamentals required."
  },
  {
    id: "j8",
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "JavaScript", "Linux"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "4–6 LPA",
    applyUrl: "https://www.zoho.com/careers/python-fresher.html",
    description: "Build products used by businesses worldwide. Zoho hires freshers and trains them in-house. You will write clean Python code, work on both backend and scripting. Problem-solving and willingness to learn are key."
  },
  {
    id: "j9",
    title: "React Developer (1-3)",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "REST APIs"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.freshworks.com/company/careers/react-1-3/",
    description: "Own frontend features for our customer engagement suite. You will build reusable components, optimize performance and collaborate with design and backend teams. At least one year of React experience is required."
  },
  {
    id: "j10",
    title: "SDE Intern",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "Algorithms", "Problem Solving", "OOPS"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹50k–₹70k/month Internship",
    applyUrl: "https://careers.microsoft.com/sde-intern-india",
    description: "Twelve-week internship on real products. You will be assigned a project and mentor. We look for strong coding skills, curiosity and teamwork. Prior internship or project experience is a plus."
  },
  {
    id: "j11",
    title: "Graduate Engineer Trainee",
    company: "Accenture",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", ".NET", "Cloud Basics", "Agile"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.accenture.com/in-en/careers/get-program",
    description: "Join our technology delivery teams after structured training. You may work on application development, testing or support. We value learning agility and good communication. Training is provided on our tech stack."
  },
  {
    id: "j12",
    title: "Backend Developer (0-1)",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Kafka", "Cassandra", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "8–12 LPA",
    applyUrl: "https://phonepe.com/careers/backend-0-1",
    description: "Build scalable systems that power India's largest digital payments platform. You will work on high-throughput services and event-driven architecture. Understanding of distributed systems and databases is preferred."
  },
  {
    id: "j13",
    title: "Frontend Developer Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "JavaScript", "CSS", "Figma"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://cred.club/careers/frontend-intern",
    description: "Help build the frontend for a product loved by millions. You will implement UI from designs, ensure responsiveness and work with the design team. Portfolio or prior frontend projects will strengthen your application."
  },
  {
    id: "j14",
    title: "DevOps Intern",
    company: "Capgemini",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Linux", "Docker", "AWS Basics", "CI/CD"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹18k–₹32k/month Internship",
    applyUrl: "https://www.capgemini.com/careers/devops-intern",
    description: "Support our DevOps and cloud teams. You will learn containerization, pipeline setup and cloud services. Basic Linux and scripting knowledge is expected. Training on AWS and tools will be provided."
  },
  {
    id: "j15",
    title: "Full Stack Developer (1-3)",
    company: "Juspay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "Node.js", "PostgreSQL", "Redis"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "12–20 LPA",
    applyUrl: "https://juspay.io/careers/fullstack-1-3",
    description: "Work on payment and checkout experiences. You will own features end-to-end from API to UI. We need developers who care about performance and user experience. Prior full stack experience is required."
  },
  {
    id: "j16",
    title: "Data Engineer Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Spark", "ETL"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "₹22k–₹38k/month Internship",
    applyUrl: "https://www.ibm.com/careers/data-engineer-intern",
    description: "Build data pipelines and support analytics. You will work with large datasets and cloud data tools. Understanding of SQL and at least one programming language is required. Training on Spark and cloud is provided."
  },
  {
    id: "j17",
    title: "Android Developer (0-1)",
    company: "Paytm",
    location: "Noida",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Kotlin", "Android SDK", "REST", "Git"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "5–8 LPA",
    applyUrl: "https://paytm.com/careers/android-0-1",
    description: "Develop features for the Paytm Android app. You will work with senior developers and follow best practices. Knowledge of Kotlin or Java and Android basics is expected. We provide mentorship and code reviews."
  },
  {
    id: "j18",
    title: "ML Engineer Intern",
    company: "Oracle",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "ML", "TensorFlow", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 7,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://www.oracle.com/careers/ml-intern-india",
    description: "Work on machine learning models and data pipelines within Oracle Cloud. You will preprocess data, train models and evaluate results. Strong Python and basic ML knowledge are required. Guidance from senior ML engineers provided."
  },
  {
    id: "j19",
    title: "Software Engineer (Fresher)",
    company: "Cognizant",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "Spring", "Testing"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.cognizant.com/careers/fresher-program",
    description: "Join our graduate program and work on client projects after training. You will develop and test software in Java or .NET. We provide comprehensive training. Good academic record and communication skills are important."
  },
  {
    id: "j20",
    title: "Product Engineer (1-3)",
    company: "Postman",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["JavaScript", "Node.js", "React", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "14–22 LPA",
    applyUrl: "https://www.postman.com/company/careers/product-engineer",
    description: "Build and improve the Postman product used by developers globally. You will own features, fix bugs and collaborate across teams. Strong JavaScript and API experience required. Remote-first culture."
  },
  {
    id: "j21",
    title: "SDE Intern",
    company: "Dell",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "Databases", "Algorithms"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹28k–₹45k/month Internship",
    applyUrl: "https://jobs.dell.com/sde-intern-india",
    description: "Work on enterprise software and infrastructure projects. You will code, test and document. We look for strong fundamentals and ability to learn. Internship can lead to a full-time offer based on performance."
  },
  {
    id: "j22",
    title: "Backend Intern",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "Redis", "MySQL"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹25k–₹42k/month Internship",
    applyUrl: "https://sharechat.com/careers/backend-intern",
    description: "Build APIs and services for our social media platform. You will work with senior engineers on scalability and features. Knowledge of Python and databases is expected. Fast-paced startup environment."
  },
  {
    id: "j23",
    title: "UI Developer (0-1)",
    company: "SAP",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["HTML", "CSS", "JavaScript", "UI Libraries"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "5–8 LPA",
    applyUrl: "https://jobs.sap.com/ui-developer-india",
    description: "Create user interfaces for SAP products. You will implement designs, ensure accessibility and work with design system. Understanding of modern CSS and JavaScript is required. Training on our frameworks provided."
  },
  {
    id: "j24",
    title: "QA Engineer (1-3)",
    company: "Thoughtworks",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Automation", "Selenium", "API Testing", "Java"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "8–14 LPA",
    applyUrl: "https://www.thoughtworks.com/careers/qa-bangalore",
    description: "Design and automate tests for client projects. You will work in agile teams and advocate for quality. Experience with test automation and scripting is required. We value collaboration and continuous learning."
  },
  {
    id: "j25",
    title: "Data Analyst (0-1)",
    company: "Ola",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["SQL", "Python", "Excel", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "5–9 LPA",
    applyUrl: "https://www.olacabs.com/careers/data-analyst",
    description: "Analyze data to support business and product decisions. You will write queries, build reports and present insights. Strong SQL and analytical thinking required. Exposure to mobility and logistics domain."
  },
  {
    id: "j26",
    title: "iOS Developer Intern",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Swift", "iOS SDK", "Xcode", "REST"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://unacademy.com/careers/ios-intern",
    description: "Build and improve the Unacademy iOS app. You will implement features and fix bugs under guidance. Knowledge of Swift and iOS basics is expected. EdTech product used by millions of learners."
  },
  {
    id: "j27",
    title: "Cloud Engineer (0-1)",
    company: "Persistent Systems",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["AWS", "Linux", "Docker", "Python"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "4–7 LPA",
    applyUrl: "https://www.persistent.com/careers/cloud-0-1",
    description: "Support cloud infrastructure and deployments. You will work with AWS, containers and automation scripts. Basic knowledge of Linux and any cloud platform is preferred. Training on AWS will be provided."
  },
  {
    id: "j28",
    title: "Full Stack Intern",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["React", "Node.js", "MongoDB", "REST"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://razorpay.com/jobs/fullstack-intern",
    description: "Work on internal tools and customer-facing features. You will build full stack applications and integrate with our APIs. Strong fundamentals in JavaScript and willingness to learn fast are important."
  },
  {
    id: "j29",
    title: "Graduate Engineer Trainee",
    company: "L&T Infotech",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "SQL", "SDLC", "Testing"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.lntinfotech.com/careers/get",
    description: "Join our graduate program and get trained on enterprise technologies. You will be deployed on projects after training. We look for good academics and learning attitude. Multiple locations possible after training."
  },
  {
    id: "j30",
    title: "Backend Developer (1-3)",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Java", "Kafka", "Elasticsearch", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 0,
    salaryRange: "12–20 LPA",
    applyUrl: "https://careers.swiggy.com/backend-1-3",
    description: "Build services that power food delivery at scale. You will work on order flow, search and real-time systems. Experience with distributed systems and message queues is required. Fast-paced product environment."
  },
  {
    id: "j31",
    title: "Frontend Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["JavaScript", "HTML", "CSS", "React"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "4–6 LPA",
    applyUrl: "https://www.zoho.com/careers/frontend-fresher.html",
    description: "Build user interfaces for Zoho's suite of products. You will work with our design system and backend APIs. Strong HTML, CSS and JavaScript fundamentals required. In-house training provided."
  },
  {
    id: "j32",
    title: "DevOps Engineer (0-1)",
    company: "Gojek",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "6–10 LPA",
    applyUrl: "https://careers.gojek.com/devops-0-1",
    description: "Maintain and improve our cloud infrastructure and deployment pipelines. You will work with Kubernetes and AWS. Basic knowledge of Linux and scripting is expected. Super-app scale and growth."
  },
  {
    id: "j33",
    title: "SDE Intern",
    company: "Google",
    location: "Hyderabad",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Algorithms", "C++/Java", "Data Structures", "Problem Solving"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹60k–₹90k/month Internship",
    applyUrl: "https://careers.google.com/sde-intern-india",
    description: "Work on impactful projects with mentorship from Google engineers. We look for strong problem-solving and coding skills. The internship includes technical training and can convert to full-time. Apply early."
  },
  {
    id: "j34",
    title: "Java Developer (1-3)",
    company: "Tech Mahindra",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "1-3",
    skills: ["Java", "Spring", "Hibernate", "REST"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.techmahindra.com/careers/java-1-3",
    description: "Develop enterprise Java applications for our clients. You will work on backend services and integrations. Strong Java and Spring experience required. Multiple client projects across domains."
  },
  {
    id: "j35",
    title: "Product Analyst Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Analytics", "A/B Testing"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "₹22k–₹38k/month Internship",
    applyUrl: "https://www.flipkartcareers.com/product-analyst-intern",
    description: "Support product and business teams with data analysis. You will run queries, build dashboards and help with experiments. Strong analytical and communication skills required. E-commerce domain exposure."
  },
  {
    id: "j36",
    title: "React Native Developer (0-1)",
    company: "CRED",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React Native", "JavaScript", "iOS", "Android"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "7–12 LPA",
    applyUrl: "https://cred.club/careers/react-native-0-1",
    description: "Build cross-platform mobile features for the CRED app. You will work with React Native and native modules when needed. Understanding of JavaScript and mobile development basics is expected. Premium product team."
  },
  {
    id: "j37",
    title: "Security Engineer Intern",
    company: "Paytm",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Networking", "Python", "Security Basics", "Linux"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://paytm.com/careers/security-intern",
    description: "Assist our security team in vulnerability assessment and tooling. You will learn about secure coding and infrastructure. Basic networking and scripting knowledge is preferred. Training on security tools provided."
  },
  {
    id: "j38",
    title: "Backend Developer (Fresher)",
    company: "Meesho",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "MySQL", "REST"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "5–8 LPA",
    applyUrl: "https://meesho.com/careers/backend-fresher",
    description: "Build backend services for India's fast-growing e-commerce platform. You will work on APIs, databases and integrations. Strong problem-solving and basic backend knowledge required. Startup culture and growth."
  },
  {
    id: "j39",
    title: "Data Science Intern",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "ML", "SQL", "Statistics"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://phonepe.com/careers/data-science-intern",
    description: "Work on ML models and analytics for payments and fraud. You will preprocess data, run experiments and document results. Strong Python and statistics foundation required. Mentorship from senior data scientists."
  },
  {
    id: "j40",
    title: "Site Reliability Engineer (0-1)",
    company: "Amazon",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Linux", "Scripting", "Monitoring", "AWS"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "8–14 LPA",
    applyUrl: "https://www.amazon.jobs/sre-india",
    description: "Keep our systems running and improve operational excellence. You will automate tasks, fix issues and work with development teams. Basic Linux and scripting skills required. On-call rotation after training."
  },
  {
    id: "j41",
    title: "UI/UX Engineer Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["HTML", "CSS", "JavaScript", "Figma"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://www.freshworks.com/company/careers/ui-intern/",
    description: "Bridge design and engineering. You will implement designs, build prototypes and work with our design system. Knowledge of front-end basics and interest in UX is expected. SaaS product experience."
  },
  {
    id: "j42",
    title: "Graduate Engineer Trainee",
    company: "HCL Technologies",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", ".NET", "SQL", "Testing"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.hcltech.com/careers/get",
    description: "Join our graduate program and get trained on industry-standard technologies. You will be assigned to projects after training. Good academic record and willingness to learn are important. Multiple streams available."
  },
  {
    id: "j43",
    title: "Node.js Developer (1-3)",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Node.js", "PostgreSQL", "Redis", "Microservices"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "14–22 LPA",
    applyUrl: "https://razorpay.com/jobs/nodejs-1-3",
    description: "Build and scale payment and banking APIs. You will own services end-to-end and work on performance. Strong Node.js and database experience required. Fintech at scale."
  },
  {
    id: "j44",
    title: "Automation Test Engineer (0-1)",
    company: "Capgemini",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Selenium", "Java", "API Testing", "TestNG"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "4–6 LPA",
    applyUrl: "https://www.capgemini.com/careers/automation-qa",
    description: "Design and develop automated test suites for client projects. You will use Selenium and API testing tools. Basic programming and testing knowledge is expected. Training on automation frameworks provided."
  },
  {
    id: "j45",
    title: "SDE Intern",
    company: "Intuit",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Databases", "Algorithms"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "₹45k–₹65k/month Internship",
    applyUrl: "https://www.intuit.com/careers/internships/sde-india",
    description: "Work on products that help millions manage their finances. You will have a project and mentor. Strong coding and problem-solving skills required. Internship often leads to pre-placement offer."
  },
  {
    id: "j46",
    title: "Frontend Developer (1-3)",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "Redux", "Performance", "Web Vitals"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "12–18 LPA",
    applyUrl: "https://www.flipkartcareers.com/frontend-1-3",
    description: "Build high-performance web experiences for millions of users. You will optimize load times and work on complex UI. At least one year of React experience and focus on performance is required."
  },
  {
    id: "j47",
    title: "Data Engineer (0-1)",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "Spark", "SQL", "Airflow"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "8–14 LPA",
    applyUrl: "https://careers.swiggy.com/data-engineer",
    description: "Build data pipelines for analytics and ML. You will work with Spark, Airflow and cloud storage. Strong SQL and Python required. Large-scale data environment."
  },
  {
    id: "j48",
    title: "Mobile Developer Intern",
    company: "Dream11",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Kotlin", "Android", "REST", "Git"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://www.dream11.com/careers/mobile-intern",
    description: "Contribute to the Dream11 Android app used by millions. You will implement features and fix bugs. Knowledge of Kotlin or Java and Android basics is expected. Sports and gaming product."
  },
  {
    id: "j49",
    title: "Full Stack Developer (0-1)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["JavaScript", "PHP", "MySQL", "React"],
    source: "LinkedIn",
    postedDaysAgo: 6,
    salaryRange: "5–8 LPA",
    applyUrl: "https://www.zoho.com/careers/fullstack-0-1.html",
    description: "Build features for Zoho's product suite. You will work on both frontend and backend. Strong fundamentals in at least one language and willingness to learn our stack are important. Bootcamp training provided."
  },
  {
    id: "j50",
    title: "Platform Engineer Intern",
    company: "Juspay",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Kafka", "Docker", "Linux"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://juspay.io/careers/platform-intern",
    description: "Work on payment infrastructure and internal platforms. You will learn distributed systems and DevOps practices. Strong programming and Linux basics required. Payments at scale."
  },
  {
    id: "j51",
    title: "Business Analyst Intern",
    company: "Accenture",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Documentation", "Stakeholder Management"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "₹18k–₹30k/month Internship",
    applyUrl: "https://www.accenture.com/in-en/careers/ba-intern",
    description: "Support project teams with requirements, analysis and reporting. You will work with clients and technical teams. Good communication and analytical skills are important. Training on tools and processes provided."
  },
  {
    id: "j52",
    title: "Python Developer (1-3)",
    company: "Oracle",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["Python", "Django", "Cloud", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "10–16 LPA",
    applyUrl: "https://www.oracle.com/careers/python-india",
    description: "Develop applications and tools on Oracle Cloud. You will work with Python, APIs and cloud services. At least one year of Python experience required. Enterprise and cloud scale."
  },
  {
    id: "j53",
    title: "SDE Intern",
    company: "Adobe",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["C++", "Java", "Algorithms", "Data Structures"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "₹50k–₹75k/month Internship",
    applyUrl: "https://career.adobe.com/internships",
    description: "Work on creative or document cloud products. You will have a project and mentor. Strong problem-solving and coding skills required. Internship can convert to full-time. Apply through career site."
  },
  {
    id: "j54",
    title: "Support Engineer (0-1)",
    company: "Freshworks",
    location: "Chennai",
    mode: "Remote",
    experience: "0-1",
    skills: ["SQL", "Troubleshooting", "APIs", "Communication"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "4–7 LPA",
    applyUrl: "https://www.freshworks.com/company/careers/support-engineer/",
    description: "Help customers resolve technical issues with our products. You will debug, write SQL and work with engineering when needed. Good communication and problem-solving skills required. Remote role."
  },
  {
    id: "j55",
    title: "React Developer (0-1)",
    company: "Innovaccer",
    location: "Noida",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["React", "JavaScript", "REST", "Redux"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "5–9 LPA",
    applyUrl: "https://innovaccer.com/careers/react-0-1",
    description: "Build UI for healthcare technology products. You will implement components and integrate with APIs. Understanding of React and JavaScript is required. Health-tech domain."
  },
  {
    id: "j56",
    title: "Backend Intern",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Ruby", "Rails", "PostgreSQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://www.browserstack.com/careers/backend-intern",
    description: "Work on the backend that powers our testing platform. You will write Ruby/Rails code and work with databases. Willingness to learn Ruby is okay if you have strong backend fundamentals. Remote-first."
  },
  {
    id: "j57",
    title: "ML Engineer (0-1)",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "TensorFlow", "SQL", "ML"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "10–16 LPA",
    applyUrl: "https://sharechat.com/careers/ml-0-1",
    description: "Build and deploy ML models for content and recommendations. You will work with large-scale data and production systems. Strong Python and ML fundamentals required. Social media scale."
  },
  {
    id: "j58",
    title: "DevOps Intern",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Docker", "Kubernetes", "AWS", "Scripting"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹35k–₹55k/month Internship",
    applyUrl: "https://phonepe.com/careers/devops-intern",
    description: "Support our platform and deployment pipelines. You will work with containers, cloud and automation. Basic Linux and scripting knowledge is expected. Payments infrastructure at scale."
  },
  {
    id: "j59",
    title: "Full Stack Developer (1-3)",
    company: "Policybazaar",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Node.js", "MongoDB", "REST"],
    source: "Indeed",
    postedDaysAgo: 7,
    salaryRange: "10–16 LPA",
    applyUrl: "https://www.policybazaar.com/careers/fullstack",
    description: "Build web applications for insurance and financial products. You will own features end-to-end. At least one year of full stack experience required. InsurTech domain."
  },
  {
    id: "j60",
    title: "Software Engineer (Fresher)",
    company: "Deloitte",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL", "Cloud Basics"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "4–6 LPA",
    applyUrl: "https://www2.deloitte.com/careers/india-freshers",
    description: "Join our technology consulting practice. You will work on client projects after training. Good academics and communication are important. Training on cloud and modern stack provided. Multiple service lines."
  }
];
